drop table if exists cat cascade;
create table cat (
	id integer generated by default as identity,
	evil boolean not null, 
	has_whiskers boolean not null, 
	length integer, 
	name varchar(255), 
	primary key (id)
);