drop table if exists cat cascade;

create table cat (
	id integer generated by default as identity,
	evil boolean not null,
	whiskers boolean not null,
	length integer,
	name varchar(225),
	primary key(id)

);